<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productos = [
            [
                'nombre' => 'Pan Tostado',
                'descripcion' => 'Muy rico',
                'imagen_url' => 'https://es.wikipedia.org/wiki/Tostada#/media/Archivo:Toast-3.jpg',
                'precio' => 10.00,
                'cantidad' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan blanco pan pequeño',
                'descripcion' => 'Muy deli',
                'imagen_url' => 'imagenes_productos/tostado.png',
                'precio' => 10.00,
                'cantidad' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Concha',
                'descripcion' => 'Pan dulce tradicional con cobertura de azúcar',
                'imagen_url' => 'imagenes_productos/concha.jpeg',
                'precio' => 12.00,
                'cantidad' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Churro',
                'descripcion' => 'Masa frita espolvoreada con azúcar y canela',
                'imagen_url' => 'imagenes_productos/churro.jpeg',
                'precio' => 8.00,
                'cantidad' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Oreja',
                'descripcion' => 'Pan en forma de oreja, crujiente y azucarado',
                'imagen_url' => 'imagenes_productos/oreja.jpeg',
                'precio' => 10.00,
                'cantidad' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cuerno',
                'descripcion' => 'Pan en forma de cuerno con sabor a mantequilla',
                'imagen_url' => 'imagenes_productos/cuerno.jpeg',
                'precio' => 9.00,
                'cantidad' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Bigote',
                'descripcion' => 'Pan dulce en forma de bigote',
                'imagen_url' => 'imagenes_productos/bigote.jpeg',
                'precio' => 11.00,
                'cantidad' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Empanada de Piña',
                'descripcion' => 'Empanada rellena de dulce de piña',
                'imagen_url' => 'imagenes_productos/empanada_pina.jpeg',
                'precio' => 13.00,
                'cantidad' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Galleta',
                'descripcion' => 'Galleta de mantequilla con azúcar',
                'imagen_url' => 'imagenes_productos/galleta.jpeg',
                'precio' => 6.00,
                'cantidad' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Campechana',
                'descripcion' => 'Pan crujiente con azúcar',
                'imagen_url' => 'imagenes_productos/campechana.jpeg',
                'precio' => 10.00,
                'cantidad' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Aquí se deben agregar más panes dulces mexicanos, hasta completar los 50 productos.
            // Los valores para 'nombre', 'descripcion', 'imagen_url', 'precio' y 'cantidad' deben ser únicos y relevantes a cada tipo de pan dulce.
            [
                'nombre' => 'Moño',
                'descripcion' => 'Pan en forma de moño, suave y dulce',
                'imagen_url' => 'imagenes_productos/mono.jpeg',
                'precio' => 10.00,
                'cantidad' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Novia',
                'descripcion' => 'Pan redondo con azúcar glass',
                'imagen_url' => 'imagenes_productos/novia.jpeg',
                'precio' => 12.00,
                'cantidad' => 115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Rebanada de Mantequilla',
                'descripcion' => 'Pan con sabor a mantequilla',
                'imagen_url' => 'imagenes_productos/rebanada_mantequilla.jpeg',
                'precio' => 11.00,
                'cantidad' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Oreja de Elefante',
                'descripcion' => 'Pan grande y crujiente',
                'imagen_url' => 'imagenes_productos/oreja_elefante.jpeg',
                'precio' => 14.00,
                'cantidad' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cuernito',
                'descripcion' => 'Pan pequeño en forma de cuerno',
                'imagen_url' => 'imagenes_productos/cuernito.jpeg',
                'precio' => 9.00,
                'cantidad' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Beso',
                'descripcion' => 'Pan redondo con relleno de crema',
                'imagen_url' => 'imagenes_productos/beso.jpeg',
                'precio' => 12.00,
                'cantidad' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Banderilla',
                'descripcion' => 'Pan en forma de banderilla con azúcar',
                'imagen_url' => 'imagenes_productos/banderilla.jpeg',
                'precio' => 8.00,
                'cantidad' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mantecada',
                'descripcion' => 'Pan dulce esponjoso con sabor a manteca',
                'imagen_url' => 'imagenes_productos/mantecada.jpeg',
                'precio' => 10.00,
                'cantidad' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Polvorón',
                'descripcion' => 'Galleta crujiente y dulce',
                'imagen_url' => 'imagenes_productos/polvoron.jpeg',
                'precio' => 7.00,
                'cantidad' => 160,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Coyota',
                'descripcion' => 'Empanada grande rellena de piloncillo',
                'imagen_url' => 'imagenes_productos/coyota.jpeg',
                'precio' => 15.00,
                'cantidad' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Buñuelo',
                'descripcion' => 'Pan frito crujiente con azúcar',
                'imagen_url' => 'imagenes_productos/bunuelo.jpeg',
                'precio' => 12.00,
                'cantidad' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Elote',
                'descripcion' => 'Pan en forma de elote con sabor dulce',
                'imagen_url' => 'imagenes_productos/elote.jpeg',
                'precio' => 10.00,
                'cantidad' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Donita',
                'descripcion' => 'Pan en forma de dona con azúcar',
                'imagen_url' => 'imagenes_productos/donita.jpeg',
                'precio' => 8.00,
                'cantidad' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cachito',
                'descripcion' => 'Pan en forma de cachito con crema',
                'imagen_url' => 'imagenes_productos/cachito.jpeg',
                'precio' => 11.00,
                'cantidad' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cocol',
                'descripcion' => 'Pan dulce con anís',
                'imagen_url' => 'imagenes_productos/cocol.jpeg',
                'precio' => 10.00,
                'cantidad' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Picón',
                'descripcion' => 'Pan redondo con azúcar',
                'imagen_url' => 'imagenes_productos/picon.jpeg',
                'precio' => 12.00,
                'cantidad' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Marranito',
                'descripcion' => 'Pan en forma de marranito con piloncillo',
                'imagen_url' => 'imagenes_productos/marranito.jpeg',
                'precio' => 13.00,
                'cantidad' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hojaldra',
                'descripcion' => 'Pan hojaldrado con azúcar',
                'imagen_url' => 'imagenes_productos/hojaldra.jpeg',
                'precio' => 11.00,
                'cantidad' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cemita',
                'descripcion' => 'Pan redondo espolvoreado con ajonjolí',
                'imagen_url' => 'imagenes_productos/cemita.jpeg',
                'precio' => 12.00,
                'cantidad' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Semita',
                'descripcion' => 'Pan dulce con piloncillo',
                'imagen_url' => 'imagenes_productos/semita.jpeg',
                'precio' => 14.00,
                'cantidad' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Calavera',
                'descripcion' => 'Pan en forma de calavera, especial para Día de Muertos',
                'imagen_url' => 'imagenes_productos/calavera.jpeg',
                'precio' => 15.00,
                'cantidad' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Puerquito',
                'descripcion' => 'Pan en forma de puerquito con sabor a piloncillo',
                'imagen_url' => 'imagenes_productos/puerquito.jpeg',
                'precio' => 13.00,
                'cantidad' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Niño Envuelto',
                'descripcion' => 'Rollo de pan con relleno de crema y frutas',
                'imagen_url' => 'imagenes_productos/nino_envuelto.jpeg',
                'precio' => 14.00,
                'cantidad' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Besito',
                'descripcion' => 'Pan pequeño con relleno de crema',
                'imagen_url' => 'imagenes_productos/besito.jpeg',
                'precio' => 12.00,
                'cantidad' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Chilindrina',
                'descripcion' => 'Pan dulce con azúcar y canela',
                'imagen_url' => 'imagenes_productos/chilindrina.jpeg',
                'precio' => 10.00,
                'cantidad' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mollete',
                'descripcion' => 'Pan redondo con azúcar y canela',
                'imagen_url' => 'imagenes_productos/mollete.jpeg',
                'precio' => 11.00,
                'cantidad' => 125,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cazuela',
                'descripcion' => 'Pan redondo y grande',
                'imagen_url' => 'imagenes_productos/cazuela.jpeg',
                'precio' => 14.00,
                'cantidad' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Galleta de Nuez',
                'descripcion' => 'Galleta dulce con trozos de nuez',
                'imagen_url' => 'imagenes_productos/galleta_nuez.jpeg',
                'precio' => 7.00,
                'cantidad' => 160,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Maíz',
                'descripcion' => 'Pan dulce con sabor a maíz',
                'imagen_url' => 'imagenes_productos/pan_maiz.jpeg',
                'precio' => 12.00,
                'cantidad' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Rosquilla',
                'descripcion' => 'Pan en forma de rosquilla con azúcar',
                'imagen_url' => 'imagenes_productos/rosquilla.jpeg',
                'precio' => 8.00,
                'cantidad' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Yema',
                'descripcion' => 'Pan dulce con yema de huevo',
                'imagen_url' => 'imagenes_productos/pan_yema.jpeg',
                'precio' => 11.00,
                'cantidad' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Canela',
                'descripcion' => 'Pan dulce con sabor a canela',
                'imagen_url' => 'imagenes_productos/pan_canela.jpeg',
                'precio' => 10.00,
                'cantidad' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Bollo',
                'descripcion' => 'Pan redondo y esponjoso',
                'imagen_url' => 'imagenes_productos/bollo.jpeg',
                'precio' => 9.00,
                'cantidad' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Muerto',
                'descripcion' => 'Pan dulce tradicional para Día de Muertos',
                'imagen_url' => 'imagenes_productos/pan_muerto.jpeg',
                'precio' => 15.00,
                'cantidad' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cemita de Agua',
                'descripcion' => 'Pan redondo con azúcar y ajonjolí',
                'imagen_url' => 'imagenes_productos/cemita_agua.jpeg',
                'precio' => 12.00,
                'cantidad' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Elote',
                'descripcion' => 'Pan dulce con sabor a elote',
                'imagen_url' => 'imagenes_productos/pan_elote.jpeg',
                'precio' => 13.00,
                'cantidad' => 95,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Avena',
                'descripcion' => 'Pan dulce con avena',
                'imagen_url' => 'imagenes_productos/pan_avena.jpeg',
                'precio' => 11.00,
                'cantidad' => 105,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Piedra',
                'descripcion' => 'Pan redondo y duro con azúcar',
                'imagen_url' => 'imagenes_productos/piedra.jpeg',
                'precio' => 14.00,
                'cantidad' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Anís',
                'descripcion' => 'Pan dulce con sabor a anís',
                'imagen_url' => 'imagenes_productos/pan_anis.jpeg',
                'precio' => 10.00,
                'cantidad' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Higo',
                'descripcion' => 'Pan dulce con higos',
                'imagen_url' => 'imagenes_productos/pan_higo.jpeg',
                'precio' => 12.00,
                'cantidad' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Plátano',
                'descripcion' => 'Pan dulce con plátano',
                'imagen_url' => 'imagenes_productos/pan_platano.jpeg',
                'precio' => 11.00,
                'cantidad' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Pasas',
                'descripcion' => 'Pan dulce con pasas',
                'imagen_url' => 'imagenes_productos/pan_pasas.jpeg',
                'precio' => 13.00,
                'cantidad' => 110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pan de Almendra',
                'descripcion' => 'Pan dulce con almendras',
                'imagen_url' => 'imagenes_productos/pan_almendra.jpeg',
                'precio' => 15.00,
                'cantidad' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('productos')->insert($productos);
    }
}
