<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProMateriaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pro_materia = [
            ['producto_id' => 1, 'materia_id' => 1, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 1, 'materia_id' => 2, 'cantidad' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 2, 'materia_id' => 3, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 2, 'materia_id' => 4, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 3, 'materia_id' => 5, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 3, 'materia_id' => 6, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 4, 'materia_id' => 7, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 4, 'materia_id' => 8, 'cantidad' => 80, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 5, 'materia_id' => 9, 'cantidad' => 70, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 5, 'materia_id' => 10, 'cantidad' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 6, 'materia_id' => 1, 'cantidad' => 90, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 6, 'materia_id' => 2, 'cantidad' => 110, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 7, 'materia_id' => 3, 'cantidad' => 130, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 7, 'materia_id' => 4, 'cantidad' => 140, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 8, 'materia_id' => 5, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 8, 'materia_id' => 6, 'cantidad' => 160, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 9, 'materia_id' => 7, 'cantidad' => 170, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 9, 'materia_id' => 8, 'cantidad' => 180, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 10, 'materia_id' => 9, 'cantidad' => 190, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 10, 'materia_id' => 10, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 11, 'materia_id' => 1, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 11, 'materia_id' => 2, 'cantidad' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 12, 'materia_id' => 3, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 12, 'materia_id' => 4, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 13, 'materia_id' => 5, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 13, 'materia_id' => 6, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 14, 'materia_id' => 7, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 14, 'materia_id' => 8, 'cantidad' => 80, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 15, 'materia_id' => 9, 'cantidad' => 70, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 15, 'materia_id' => 10, 'cantidad' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 16, 'materia_id' => 1, 'cantidad' => 90, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 16, 'materia_id' => 2, 'cantidad' => 110, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 17, 'materia_id' => 3, 'cantidad' => 130, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 17, 'materia_id' => 4, 'cantidad' => 140, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 18, 'materia_id' => 5, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 18, 'materia_id' => 6, 'cantidad' => 160, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 19, 'materia_id' => 7, 'cantidad' => 170, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 19, 'materia_id' => 8, 'cantidad' => 180, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 20, 'materia_id' => 9, 'cantidad' => 190, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 20, 'materia_id' => 10, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 21, 'materia_id' => 1, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 21, 'materia_id' => 2, 'cantidad' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 22, 'materia_id' => 3, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 22, 'materia_id' => 4, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 23, 'materia_id' => 5, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 23, 'materia_id' => 6, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 24, 'materia_id' => 7, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 24, 'materia_id' => 8, 'cantidad' => 80, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 25, 'materia_id' => 9, 'cantidad' => 70, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 25, 'materia_id' => 10, 'cantidad' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 26, 'materia_id' => 1, 'cantidad' => 90, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 26, 'materia_id' => 2, 'cantidad' => 110, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 27, 'materia_id' => 3, 'cantidad' => 130, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 27, 'materia_id' => 4, 'cantidad' => 140, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 28, 'materia_id' => 5, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 28, 'materia_id' => 6, 'cantidad' => 160, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 29, 'materia_id' => 7, 'cantidad' => 170, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 29, 'materia_id' => 8, 'cantidad' => 180, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 30, 'materia_id' => 9, 'cantidad' => 190, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 30, 'materia_id' => 10, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 31, 'materia_id' => 1, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 31, 'materia_id' => 2, 'cantidad' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 32, 'materia_id' => 3, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 32, 'materia_id' => 4, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 33, 'materia_id' => 5, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 33, 'materia_id' => 6, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 34, 'materia_id' => 7, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 34, 'materia_id' => 8, 'cantidad' => 80, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 35, 'materia_id' => 9, 'cantidad' => 70, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 35, 'materia_id' => 10, 'cantidad' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 36, 'materia_id' => 1, 'cantidad' => 90, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 36, 'materia_id' => 2, 'cantidad' => 110, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 37, 'materia_id' => 3, 'cantidad' => 130, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 37, 'materia_id' => 4, 'cantidad' => 140, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 38, 'materia_id' => 5, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 38, 'materia_id' => 6, 'cantidad' => 160, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 39, 'materia_id' => 7, 'cantidad' => 170, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 39, 'materia_id' => 8, 'cantidad' => 180, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 40, 'materia_id' => 9, 'cantidad' => 190, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 40, 'materia_id' => 10, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 41, 'materia_id' => 1, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 41, 'materia_id' => 2, 'cantidad' => 50, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 42, 'materia_id' => 3, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 42, 'materia_id' => 4, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 43, 'materia_id' => 5, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 43, 'materia_id' => 6, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 44, 'materia_id' => 7, 'cantidad' => 100, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 44, 'materia_id' => 8, 'cantidad' => 80, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 45, 'materia_id' => 9, 'cantidad' => 70, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 45, 'materia_id' => 10, 'cantidad' => 60, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 46, 'materia_id' => 1, 'cantidad' => 90, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 46, 'materia_id' => 2, 'cantidad' => 110, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 47, 'materia_id' => 3, 'cantidad' => 130, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 47, 'materia_id' => 4, 'cantidad' => 140, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 48, 'materia_id' => 5, 'cantidad' => 150, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 48, 'materia_id' => 6, 'cantidad' => 160, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 49, 'materia_id' => 7, 'cantidad' => 170, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 49, 'materia_id' => 8, 'cantidad' => 180, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 50, 'materia_id' => 9, 'cantidad' => 190, 'created_at' => now(), 'updated_at' => now()],
            ['producto_id' => 50, 'materia_id' => 10, 'cantidad' => 200, 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('pro_materia')->insert($pro_materia);
    }
}
